#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BSP_DIR="${ROOT_DIR}/bsp/qemu-vexpress-a9"

if [ ! -d "${BSP_DIR}" ]; then
  echo "Error: BSP dir not found: ${BSP_DIR}"
  exit 1
fi

echo "[clean] BSP: ${BSP_DIR}"

# Generated build artifacts and runtime files.
rm -rf "${BSP_DIR}/build"
rm -rf "${BSP_DIR}/__pycache__"
rm -f "${BSP_DIR}/.sconsign.dblite"
rm -f "${BSP_DIR}/rtthread.elf" "${BSP_DIR}/rtthread.bin" "${BSP_DIR}/rtthread.map"
rm -f "${BSP_DIR}/rtt.asm"
rm -f "${BSP_DIR}/sd.bin"

# Auto-generated by rtconfig.py during build.
rm -f "${BSP_DIR}/drivers/automac.h"

echo "[clean] done"
